// Aircraft Types
const vfrList = [
    { name: "Piper P28 Cherokee", type: "P28A", wtc: "L", speed: { min: 80, max: 110 } },
    { name: "Cessna 172 Skyhawk", type: "C172", wtc: "L", speed: { min: 90, max: 120 } },
    { name: "Diamond Twin Star", type: "DA42", wtc: "L", speed: { min: 140, max: 170 } },
    { name: "Piper PA31", type: "PA31", wtc: "L", speed: { min: 120, max: 200 } },
    { name: "Cessna 208 Grand Caravan", type: "C208", wtc: "L", speed: { min: 115, max: 160 } },
    { name: "Beech 200 Super King Air", type: "BE20", wtc: "L", speed: { min: 145, max: 250 } },
    { name: "Socata TBM-700", type: "TBM7", wtc: "L", speed: { min: 115, max: 240 } },
    { name: "Pilatus PC-12 Eagle", type: "PC12", wtc: "L", speed: { min: 130, max: 210 } },
    { name: "Robin Cadet", type: "DR40", wtc: "L", speed: { min: 100, max: 140 } },
    { name: "Beech 33 Debonair", type: "BE33", wtc: "L", speed: { min: 105, max: 160 } },
    { name: "Diamond DA20 Katana", type: "DV20", wtc: "L", speed: { min: 90, max: 140 } },
    { name: "Socata TB-21", type: "TB21", wtc: "L", speed: { min: 100, max: 180 } },
    { name: "Cirrus SR22", type: "SR22", wtc: "L", speed: { min: 90, max: 180 } },
    { name: "Aquila A 210", type: "A210", wtc: "L", speed: { min: 90, max: 150 } },
    { name: "Aerospool WT9 Dynamic", type: "WT9", wtc: "L", speed: { min: 60, max: 120 } },
    { name: "Cessna 152", type: "C152", wtc: "L", speed: { min: 85, max: 100 } }
]

const ifrList = [
    { name: "Cessna 402 Businessliner", type: "C402", wtc: "L", speed: { min: 125, max: 220 } },
    { name: "ATR-72", type: "AT72", wtc: "M", speed: { min: 140, max: 260 } },
    { name: "De Havilland Canada Dash 8 Q100", type: "DH8A", wtc: "M", speed: { min: 130, max: 250 } },
    { name: "Cessna 550 Citation", type: "C550", wtc: "L", speed: { min: 145, max: 250 } },
    { name: "Raytheon 800 XP Hawker", type: "H25B", wtc: "M", speed: { min: 155, max: 290 } },
    { name: "Learjet 60", type: "LJ60", wtc: "M", speed: { min: 170, max: 290 } },
    { name: "Bombardier Regional Jet CRJ-900", type: "CRJ9", wtc: "M", speed: { min: 165, max: 290 } },
    { name: "Embraer ERJ-145", type: "E145", wtc: "M", speed: { min: 165, max: 250 } },
    { name: "BAE Systems AVRO RJ-100", type: "RJ1H", wtc: "M", speed: { min: 155, max: 250 } },
    { name: "Boeing 737", type: "B737", wtc: "M", speed: { min: 165, max: 280 } },
    { name: "Airbus A320", type: "A320", wtc: "M", speed: { min: 175, max: 290 } },
    { name: "Airbus A340-300", type: "A343", wtc: "H", speed: { min: 175, max: 290 } },
    { name: "Boeing 777", type: "B773", wtc: "H", speed: { min: 200, max: 300 } },
    { name: "SAAB 2000", type: "SB20", wtc: "M", speed: { min: 140, max: 340 } },
    { name: "Fokker 50", type: "F50", wtc: "M", speed: { min: 130, max: 220 } },
    { name: "ATR-42-500", type: "AT45", wtc: "M", speed: { min: 140, max: 230 } },
    { name: "British Aerospace Jetstream 32", type: "JS32", wtc: "M", speed: { min: 140, max: 240 } },
    { name: "Dassault Falcon 2000", type: "F2TH", wtc: "M", speed: { min: 150, max: 290 } },
    { name: "Dassault Falcon 50", type: "FA50", wtc: "M", speed: { min: 150, max: 290 } },
    { name: "Fokker F100", type: "F100", wtc: "M", speed: { min: 165, max: 250 } },
    { name: "Airbus A321", type: "A321", wtc: "M", speed: { min: 175, max: 290 } },
    { name: "Airbus A319", type: "A319", wtc: "M", speed: { min: 165, max: 290 } },
    { name: "Airbus A318", type: "A318", wtc: "M", speed: { min: 165, max: 290 } },
    { name: "Boeing 737-800", type: "B738", wtc: "M", speed: { min: 165, max: 280 } },
    { name: "Airbus A330-300", type: "A333", wtc: "H", speed: { min: 175, max: 290 } },
    { name: "Boeing 767-400", type: "B764", wtc: "H", speed: { min: 190, max: 290 } },
    { name: "Boeing 787-8 Dreamliner", type: "B788", wtc: "H", speed: { min: 190, max: 300 } },
    { name: "Airbus A350-900", type: "A359", wtc: "H", speed: { min: 220, max: 250 } },
    { name: "Antonov An-124 Ruslan", type: "A124", wtc: "H", speed: { min: 160, max: 290 } },
    { name: "Boeing 747-400", type: "B744", wtc: "H", speed: { min: 215, max: 300 } },
    { name: "Airbus A380-800", type: "A388", wtc: "J", speed: { min: 190, max: 300 } }
]

const milList = [
    { name: "General Dynamics F-16 Fighting Falcon", type: "F16", wtc: "M", speed: { min: 175, max: 350 } },
    { name: "Lockheed Martin F-35 Lightning II", type: "F35", wtc: "M", speed: { min: 190, max: 350 } }
]

const heliList = [
    { name: "Robinson R-44", type: "R44", wtc: "L", speed: { min: 60, max: 100 } },
    { name: "Aerospatiale AS-350 Ecureuil", type: "AS50", wtc: "L", speed: { min: 70, max: 120 } },
    { name: "Airbus Helicopters H215", type: "AS32", wtc: "M", speed: { min: 80, max: 130 } },
    { name: "EUROCOPTER EC-135", type: "EC35", wtc: "L", speed: { min: 70, max: 120 } }
]

// Callsigns
const airlineCode = [
    { icao: "AAL", callsign: "american" },
    { icao: "ACA", callsign: "air canada" },
    { icao: "AFR", callsign: "air france" },
    { icao: "AUA", callsign: "austrian" },
    { icao: "BAW", callsign: "speedbird" },
    { icao: "BTI", callsign: "air baltic" },
    { icao: "AAB", callsign: "abelag" },
    { icao: "AIC", callsign: "air inida" },
    { icao: "ANA", callsign: "all nippon" },
    { icao: "ASL", callsign: "air serbia" },
    { icao: "BEL", callsign: "beeline" },
    { icao: "BLX", callsign: "bluescan" },
    { icao: "CAI", callsign: "corendon" },
    { icao: "CAO", callsign: "airchina freight" },
    { icao: "CES", callsign: "china eastern" },
    { icao: "CHH", callsign: "hainan" },
    { icao: "CLG", callsign: "challair" },
    { icao: "CTN", callsign: "croatia" },
    { icao: "CYP", callsign: "cyprair" },
    { icao: "DAL", callsign: "delta" },
    { icao: "DLA", callsign: "dolomiti" },
    { icao: "DLH", callsign: "lufthansa" },
    { icao: "EDW", callsign: "edelweiss" },
    { icao: "EIN", callsign: "shamrock" },
    { icao: "EJA", callsign: "execjet" },
    { icao: "EJU", callsign: "alpine" },
    { icao: "ETD", callsign: "etihad" },
    { icao: "ETH", callsign: "ethiopian" },
    { icao: "EWG", callsign: "eurowings" },
    { icao: "EXS", callsign: "channex" },
    { icao: "EZY", callsign: "easy" },
    { icao: "FDX", callsign: "fedex" },
    { icao: "FIN", callsign: "finair" },
    { icao: "IBE", callsign: "iberia" },
    { icao: "ICE", callsign: "iceair" },
    { icao: "ITY", callsign: "itarrow" },
    { icao: "JAF", callsign: "beauty" },
    { icao: "JBU", callsign: "jetblue" },
    { icao: "JIA", callsign: "blue streak" },
    { icao: "KAL", callsign: "korean air" },
    { icao: "KLM", callsign: "klm" },
    { icao: "LGL", callsign: "luxair" },
    { icao: "LOT", callsign: "lot" },
    { icao: "MAC", callsign: "arabia maroc" },
    { icao: "MXY", callsign: "moxy" },
    { icao: "NFA", callsign: "north flying" },
    { icao: "NJE", callsign: "fraction" },
    { icao: "NOZ", callsign: "nordic" },
    { icao: "NSZ", callsign: "rednose" },
    { icao: "OCN", callsign: "ocean" },
    { icao: "PGT", callsign: "sunturk" },
    { icao: "QTR", callsign: "qatari" },
    { icao: "RJA", callsign: "jordanian" },
    { icao: "ROT", callsign: "tarom" },
    { icao: "RPA", callsign: "brickyard" },
    { icao: "ROU", callsign: "rouge" },
    { icao: "RYR", callsign: "ryanair" },
    { icao: "SAS", callsign: "scandinavian" },
    { icao: "SIA", callsign: "singapore" },
    { icao: "SVA", callsign: "saudia" },
    { icao: "SWA", callsign: "southwest" },
    { icao: "SWR", callsign: "swiss" },
    { icao: "TAP", callsign: "air portugal" },
    { icao: "THA", callsign: "thai" },
    { icao: "THY", callsign: "turkish" },
    { icao: "TOM", callsign: "tom jet" },
    { icao: "TRA", callsign: "transavia" },
    { icao: "TSC", callsign: "air transat" },
    { icao: "TUI", callsign: "tui jet" },
    { icao: "TVS", callsign: "skytravel" },
    { icao: "UAE", callsign: "emirates" },
    { icao: "UAL", callsign: "united" },
    { icao: "UPS", callsign: "ups" },
    { icao: "VIR", callsign: "virgin express" },
    { icao: "VKG", callsign: "viking" },
    { icao: "VLG", callsign: "vueling" },
    { icao: "VOE", callsign: "volotea" },
    { icao: "WIF", callsign: "wideroe" },
    { icao: "WJA", callsign: "westjet" },
    { icao: "WZZ", callsign: "wizzair" }
]

// This is difficult because callsign are actually linked to types of aircraft.
// Perhaps I should create a separate military list
const milCallsign = [
    "REDARROW",
    "LHOB",
    "MILAN",
    "REF",
    "BENGA",
    "VOLPE",
    "FIAMM",
    "HKY",
    "RRR",
    "HR",
    "VVAJ",
    "BAF",
    "RCH",
    "CFC",
    "SPARTA",
    "BRK",
    "ROF",
    "OR",
    "COBRA",
    "SRA",
    "RNGR",
    "BOMR"
]

const vfrCallsign = [
    { country: "Belgium", countryCode: "OO", presentation: "PZZ" },
    { country: "Austria", countryCode: "OE", presentation: "KZZ" },
    { country: "Bulgaria", countryCode: "LZ", presentation: "ZZZ" },
    { country: "Czech Republic", countryCode: "OK", presentation: "ZZZ" },
    { country: "Slovakia", countryCode: "OM", presentation: "ZZZ" },
    { country: "Estonia", countryCode: "ES", presentation: "ZZZ" },
    { country: "Isle of Man", countryCode: "M", presentation: "ZZZZ" },
    { country: "Finland", countryCode: "OH", presentation: "ZZZ" },
    { country: "Germany", countryCode: "DE", presentation: "ZZZ" },
    { country: "France", countryCode: "F", presentation: "ZZZZ" },
    { country: "Italy", countryCode: "I", presentation: "ZZZZ" },
    { country: "Hungary", countryCode: "HA", presentation: "ZZZ" },
    { country: "Ireland", countryCode: "IE", presentation: "ZZZ" },
    { country: "Latvia", countryCode: "YL", presentation: "ZZZ" },
    { country: "Lithuania", countryCode: "LY", presentation: "ZZZ" },
    { country: "Luxembourg", countryCode: "LX", presentation: "ZZZ" },
    { country: "Netherlands", countryCode: "PH", presentation: "ZZZ" },
    { country: "Norway", countryCode: "LN", presentation: "ZZZ" },
    { country: "Poland", countryCode: "SP", presentation: "ZZZ" },
    { country: "Portugal", countryCode: "CR", presentation: "ZZZ" },
    { country: "Spain", countryCode: "EC", presentation: "WZZ" },
    { country: "Sweden", countryCode: "SE", presentation: "ZZZ" },
    { country: "Switzerland", countryCode: "HB", presentation: "ZZZ" },
    { country: "Serbia", countryCode: "YU", presentation: "ZZZ" },
    { country: "United Kingdom", countryCode: "G", presentation: "ZZZZ" },
    { country: "United States", countryCode: "N", presentation: "1AA-999ZZ" },
    { country: "Denmark", countryCode: "OY", presentation: "ZZZ" }
]